### ISSUE TITLE
Unexpected token: ...

### ISSUE THREAD

**Issue by zavalit** [phpmd/phpmd#397] opened 2016-09-08 13:02 UTC
it can not check the spread operator "..." in case it is used in a method call.

```php
function foo(...$arg){
 // implementation
}

foo(...[1,2,3]) // this place rise an "Unexpected token: ...,  line: 5, " error
```

**Comment by ravage84** [comment] 2016-09-08 15:42
Closing, duplicate of #279

**Closed by ravage84** 2016-09-08 15:42 UTC
Labels: Bug
