### ISSUE TITLE
Support for group use declaration (PHP7)

### ISSUE THREAD

**Issue by PierreLvx** [phpmd/phpmd#342] opened 2016-01-27 10:30 UTC
With PHP 7:

> Classes, functions and constants being imported from the same namespace can now be grouped together in a single use statement.

[Source + example code](http://php.net/manual/fr/migration70.new-features.php#migration70.new-features.group-use-declarations).

With the following code:

```php
use App\Http\Models\{User, UserOrigin, Website};
```

This happens :

```
Unexpected token: {, line: 13, col: 21, file: (...).
```

**Comment by ravage84** [comment] 2016-03-02 10:15
Closing as it is a duplicate of https://github.com/phpmd/phpmd/issues/327

**Closed by ravage84** 2016-03-02 10:15 UTC
Labels: Enhancement
