### ISSUE TITLE
Unexpected token: ... in PHP 5.6

### ISSUE THREAD

**Issue by Schodemeiss** [phpmd/phpmd#353] opened 2016-03-02 12:02 UTC
When running phpmd-2.3.2.phar via php5.6 in CLI, I get the following token error:

Unexpected token: ...,

I guess this is the "splat" operator not being recognised?

**Comment by ravage84** [comment] 2016-03-02 13:49
This is probably related to pdepend.
Also seems to be a duplicate of https://github.com/phpmd/phpmd/issues/279

**Closed by ravage84** 2016-03-02 13:49 UTC
Labels: Bug, PDepend
