### ISSUE TITLE
"PHP Notice: Use of undefined constant T_CHARACTER" Persists

### ISSUE THREAD

**Issue by ajax13** [phpmd/phpmd#526] opened 2017-10-11 11:40 UTC
I have notice that you fix this issue since V2.3.3 as described here #338 
Unfortunately, I have got the same problem for V2.5.0 as well.

#Error message:
```
[phpmd] PHP Notice:  Use of undefined constant T_CHARACTER - assumed 'T_CHARACTER' in /usr/share/php/PHP/Depend.php on line 538
    [phpmd] PHP Stack trace:
    [phpmd] PHP   1. {main}() /usr/bin/phpmd:0
    [phpmd] PHP   2. PHP_PMD_TextUI_Command::main() /usr/bin/phpmd:48
    [phpmd] PHP   3. PHP_PMD_TextUI_Command->run() /usr/share/php/PHP/PMD/TextUI/Command.php:154
    [phpmd] PHP   4. PHP_PMD->processFiles() /usr/share/php/PHP/PMD/TextUI/Command.php:129
    [phpmd] PHP   5. PHP_PMD_Parser->parse() /usr/share/php/PHP/PMD.php:203
    [phpmd] PHP   6. PHP_Depend->analyze() /usr/share/php/PHP/PMD/Parser.php:128
    [phpmd] PHP   7. PHP_Depend->performParseProcess() /usr/share/php/PHP/Depend.php:306
    [phpmd] PHP Notice:  Use of undefined constant T_BAD_CHARACTER - assumed 'T_BAD_CHARACTER' in /usr/share/php/PHP/Depend.php on line 538
```
#Environment
$ php -v
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

#Test case
`phpmd src text phpmd.xml`

#phpmd.xml
```
<ruleset name="my project"
         xmlns="http://pmd.sf.net/ruleset/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sf.net/ruleset/1.0.0 http://pmd.sf.net/ruleset_xml_schema.xsd"
         xsi:noNamespaceSchemaLocation="http://pmd.sf.net/ruleset_xml_schema.xsd">
    <description>My project</description>

    <rule ref="rulesets/codesize.xml/CyclomaticComplexity" />
    <rule ref="rulesets/codesize.xml/NPathComplexity" />
    <rule ref="rulesets/codesize.xml/ExcessiveClassComplexity" />
    <rule ref="rulesets/codesize.xml/ExcessiveClassLength" />
    <rule ref="rulesets/codesize.xml/ExcessiveMethodLength" />
    <rule ref="rulesets/codesize.xml/ExcessiveParameterList" />
</ruleset>
```

**Comment by ravage84** [comment] 2017-10-12 12:38
What version of Pdepend are you using? If I recall correctly, the newest version of it should fully support PHP 7.**0**.

**Comment by ajax13** [comment] 2017-10-12 14:44
Pdepend => 2.0.6

**Comment by ravage84** [comment] 2017-10-12 14:50
Can you verify that behavior with pdepend 2.5.0, please?

https://pdepend.org/news/pdepend-2.5.0-released.html

**Comment by ajax13** [comment] 2017-10-12 14:54
my bad, I am actualy on:

$ pdepend --version
PDepend 2.5.0

**Comment by ravage84** [comment] 2017-10-12 15:04
Since the error happens in Pdepend, I would suggest you to raise an issue [there](https://github.com/pdepend/pdepend/):

```` php
[phpmd] PHP   7. PHP_Depend->performParseProcess() /usr/share/php/PHP/Depend.php:306
    [phpmd] PHP Notice:  Use of undefined constant T_BAD_CHARACTER - assumed 'T_BAD_CHARACTER' in /usr/share/php/PHP/Depend.php on line 538
````

**Comment by ajax13** [comment] 2017-10-12 15:21
okey, thx @ravage84

**Comment by tvbeek** [comment] 2019-09-24 15:49
@ajax13 can you verify this with the latest pdepend version? It should be fixed but I like to be sure before closing the issue.

**Comment by kylekatarnls** [comment] 2019-12-22 18:47
`T_CHARACTER` is defined in PDepend since the version 2.2.0 so this should be fixed with the last version, if you can reproduce with the latest version, please give the new stack trace and the file you use to reproduce the bug and I will re-open.

**Closed by kylekatarnls** 2019-12-22 18:47 UTC
Labels: Bug, Needs Feedback, On Hold, PDepend, php7.0
