### ISSUE TITLE
force unusedcode for "global" variables

### ISSUE THREAD

**Issue by SailorMax** [phpmd/phpmd#298] opened 2015-08-04 09:58 UTC
Can you add parameter for "unusedcode" or some kind of markup per file (/* phpmd: unusedcode=+global_vars */) to detect unused variables in global name space?

My engine has directory, from where it take files from system function => all that files are source of function, which has include() => we can detect unused variables inside that files.

Sample:
file:
``` php
<? /* phpmd: unusedcode=+global_vars */
 $foo = 12;
?>
```

Exp: "Avoid unused local variables such as '$foo'."
Act: nothing

**Comment by ravage84** [comment] 2016-06-27 12:05
Duplicate of #294

**Closed by ravage84** 2016-06-27 12:05 UTC
Labels: Feature
