### ISSUE TITLE
Null coalescing operator error using php 7

### ISSUE THREAD

**Issue by bmxevsy** [phpmd/phpmd#374] opened 2016-06-14 08:42 UTC
According to the new feature in php 7
>>The null coalescing operator (??) has been added as syntactic sugar for the common case of needing to use a ternary in conjunction with isset(). It returns its first operand if it exists and is not NULL; otherwise it returns its second operand.

PHPMD provides an error:
**Unexpected token: ??**

Could it be fixed?

**Comment by ravage84** [comment] 2016-06-14 08:58
Thanks for reporting.
Duplicate of https://github.com/phpmd/phpmd/issues/347

**Closed by ravage84** 2016-06-14 08:58 UTC
Labels: Bug
