### ISSUE TITLE
take files in via stdin, output report via stdout

### ISSUE THREAD

**Issue by contra** [phpmd/phpmd#186] opened 2014-09-10 00:38 UTC
Specifying file paths is totally wrong when using this in conjunction with other tools

**Comment by BenjaminPaap** [comment] 2015-04-07 09:50
+1 for this

**Comment by ravage84** [comment] 2015-06-05 00:42
Closing as it is a duplicate of https://github.com/phpmd/phpmd/issues/185

**Closed by ravage84** 2015-06-05 00:42 UTC
Labels: Enhancement
