### ISSUE TITLE
Phar archive is not available

### ISSUE THREAD

**Issue by DmitryNaum** [phpmd/phpmd#619] opened 2019-07-04 17:42 UTC
On installation page described instruction for installing phpmd via phar release, but, specified link `http://static.phpmd.org/php/latest/phpmd.phar` is not available.

Seems like `static.phpmd.org` has not DNS A records 
https://mxtoolbox.com/SuperTool.aspx?action=a%3astatic.phpmd.org&run=toolpage

**Comment by ravage84** [comment] 2019-07-04 21:56
Thank you, @DmitryNaum , for letting us know.
We are aware of the situation. We are working on it. No estimate, yet.

Duplicate of #155  Closing.

**Comment by ravage84** [comment] 2019-07-09 14:48
Reopen, as there is no issue we track this.

**Comment by harshild** [comment] 2019-07-11 06:49
+1

looks like http://static.phpmd.org is not available , and hence the archive.

try using this link directly http://static.phpmd.org/php/latest/phpmd.phar

**Comment by kylekatarnls** [comment] 2019-07-11 07:03
Phar files will be on https://github.com/phpmd/phpmd/releases

Restoring static.phpmd.org or not is in discussion.

**Comment by harshild** [comment] 2019-07-11 07:52
in that case brew package needs to be updated accordingly. I will try to find how that can be done.

**Comment by caaguado** [comment] 2019-07-21 15:11
Hi,

Please make http://static.phpmd.org/php/latest/phpmd.phar available back again, as Github storage makes automatic updates quite hard, as you first need to know what's the latest revision, which will in one way or another require additional metainfo parsing. And that's not very sustainable over time.

Thanks!

**Comment by tvanrielwendrich** [comment] 2019-11-28 09:49
Hey, I hate bringing this up. But what is the exact reason for taking down the link and [still having the link on the Downloads page](https://phpmd.org/download/index.html#installing-as-a-phar)? I am relying on the static link for building a docker container with phpmd in it.

**Comment by tvbeek** [comment] 2019-11-28 09:51
@tvanrielwendrich That is a very good question and the reason that I created #682 to add a working phar link.

**Comment by Rarst** [comment] 2019-11-30 20:51
FYI if phar files are attached to github releases and consistently named, it's now possible to link to the file in latest release like this: https://github.com/phpmd/phpmd/releases/latest/download/phpmd.phar

**Comment by kylekatarnls** [comment] 2019-12-01 10:24
Hi @Rarst do you know if the GitHub "latest" will give us the higher number or latest date? And also if it excludes pre-releases?

**Comment by Rarst** [comment] 2019-12-01 10:44
It will be the release marked as "Latest release" on https://github.com/phpmd/phpmd/releases. They are ordered by _release_ date (not _tag_ date). Don't know how pre-releases are handled in regards to this.

**Comment by kylekatarnls** [comment] 2019-12-01 11:04
Indeed it can create some troubles for us. We will probably not stop maintaining 2.x when 3.0 will be released this means if we publish 2.9.0 after 3.0.0, the documentation link will take it. Same for a 2.8.1 patch we would release after 2.9.0.

But meanwhile, this link would be better than a dead link. So I propose to put it in the doc.

Thanks @Rarst!

**Comment by kylekatarnls** [comment] 2019-12-23 15:04
Static download is up again through the URL
https://phpmd.org/static/latest/phpmd.phar
Or for specific versions (from 2.6.1):
https://phpmd.org/static/2.7.0/phpmd.phar

**Closed by kylekatarnls** 2019-12-23 15:04 UTC
Labels: Website
