### ISSUE TITLE
--exclude CLI parameter Only Skips Some Files

### ISSUE THREAD

**Issue by loeffel-io** [phpmd/phpmd#634] opened 2019-07-16 16:24 UTC
**Without exclude option:**

```bash
./vendor/bin/phpmd ./src/ text ./ruleset.xml
```

```
.../src/Migrations/Version20190624122708.php:20   Avoid unused parameters such as '$schema'.
.../src/Migrations/Version20190624122708.php:37   Avoid unused parameters such as '$schema'.
.../src/Migrations/Version20190716104416.php:20   Avoid unused parameters such as '$schema'.
.../src/Migrations/Version20190716104416.php:28   Avoid unused parameters such as '$schema'.
```

**With exclude option:**

```bash
./vendor/bin/phpmd ./src/ text ./ruleset.xml --exclude src/Migrations/*
```

```
.../src/Migrations/Version20190716104416.php:20   Avoid unused parameters such as '$schema'.
.../src/Migrations/Version20190716104416.php:28   Avoid unused parameters such as '$schema'.
```

**Comment by kylekatarnls** [comment] 2019-07-16 17:59
Hi @loeffel-io, would you be able to produce a zip with sample files which one we could reproduce the bug?

**Comment by tvbeek** [comment] 2020-03-10 20:24
Closing because we didn't get the feedback needed to reproduce the bug.

**Closed by tvbeek** 2020-03-10 20:24 UTC
Labels: Bug, CLI, Needs Feedback
