### ISSUE TITLE
Incorrect "Avoid unused private methods" issue

### ISSUE THREAD

**Issue by YiiRocks** [phpmd/phpmd#502] opened 2017-07-18 18:50 UTC
Private functions called from preg_replace_callback_array are not recognized as being used. Therefor, an incorrect "Avoid unused private methods" issue will be created.

**Comment by Thoulah** [comment] 2017-07-22 12:41
Example code:

```
public function cleanInput(string $data): string {
	$data = preg_replace_callback_array([
		'/(vimeo):(()?[[:digit:]]+):(16by9|4by3)/U'		=> 'self::getVideo',
		'/(youtube):((PL)?[[:ascii:]]{11,32}):(16by9|4by3)/U'	=> 'self::getVideo',
	], $data);
}

private function getVideo(array $match): string {
	return Video::getVideo($match[1], $match[2], $match[4], $match[3]);
}
```

The private function `getVideo` is not recognized as being used.

**Comment by ktomk** [comment] 2017-07-26 17:15
I don't know if this requires a new ticket, but I can also confirm that private function use from a self::static_method() is not recognized either. I don't know what's common in this project, does this require a new issue?

**Comment by ravage84** [comment] 2017-07-27 10:38
@ktomk no, it's not necessary. I think both issues can be worked on at once.

**Comment by sp72** [comment] 2017-12-07 15:52
+1 for the use in a static method.
Thanks for the (incoming ?) fix ! :)

```php
class A
{
  public static function test()
  {
    $obj = new self;
    $obj->usePrivateMethod();
  }

  private function usePrivateMethod() // Marked as used
  {
  }
}
```

**Comment by johnsaigle** [comment] 2019-12-02 18:30
I'm having a similar issue with this code:

```php
    private static function _formatDicomTars(DicomTarDTO $dicom): array
    {
        return array(
            'Tarname'    => $dicom->getTarname(),
            'SeriesInfo' => array_map(
                'self::_formatSeries',
                $dicom->getSeries()
            ),
        );
    }

    private static function _formatSeries(DicomSeriesDTO $series): array
    {
       ...
    }
```

`_formatSeries()` here is flagged as unused but it is used as a callback.

**Comment by cawolf** [comment] 2020-01-14 10:18
Same issue probably applies to the usage of `usort()` and similar functions:

```php
    public function sort(IteratorAggregate $services)
    {
        usort($services, [$this, 'sortByPriority']);
        ...
    }

    private function sortByPriority(ServiceInterface $serviceA, ServiceInterface $serviceB): int
    {
        ...
    }

```

**Comment by markuspoerschke** [comment] 2020-09-27 10:34
I can confirm the issue with the following example class:

```php
class Property
{
    /**
     * @var array<int, Parameter>
     */
    private array $parameters = [];

    /**
     * @param Parameter[] $parameters
     */
    public function __construct(array $parameters = [])
    {
        array_walk($parameters, [$this, 'addParameter']);
    }

    private function addParameter(Parameter $parameter): void
    {
        $this->parameters[] = $parameter;
    }
}
```

The private method `addParameter` is claimed unused, but it is used within the `array_walk(...)` function call.

**Comment by kylekatarnls** [comment] 2020-09-28 16:40
Actually we basically detect only method called with `::` or `->`. The array and string callable syntaxes support has never been implemented. It would probably need first for PDepend to support it.

Pull-requests for that would be gladly accepted.

**Comment by kylekatarnls** [comment] 2024-02-17 16:16
For the record, here is fix proposal for the `[$this, 'foo']` syntax: #1068

Since `self::foo` syntax is now deprecated, I'm not sure we should do anything to support it.

Other comments about `new self` or so are different concerns already tracked in separated issues.

So I suggest we close this issue after merging #1068.

**Closed** 2024-02-17 17:49 UTC
Labels: Bug, UnusedPrivateMethod
