### ISSUE TITLE
Add rule that detects access to an undefined variable

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#38] opened 2012-06-20 19:57 UTC
Implement a rule that detects property or method access on a variable that is not defined.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/11009501']

**Comment by ava-dylang** [comment] 2015-03-30 23:45
:+1: how do php people even live without any tool to do this. :moyai:-age

**Comment by ravage84** [comment] 2015-06-05 00:19
Probably related to or even a duplicate of https://github.com/phpmd/phpmd/issues/65

**Comment by ravage84** [comment] 2017-06-03 02:04
Closing as it's a duplicate of https://github.com/phpmd/phpmd/issues/65

**Closed by ravage84** 2017-06-03 02:04 UTC
Labels: Feature
