### ISSUE TITLE
Faulty phar SHA512 signature verification

### ISSUE THREAD

**Issue by adamculp** [phpmd/phpmd#376] opened 2016-06-14 19:59 UTC
When attempting to use the phpmd.phar with PHP 7 via CLI I receive the following error:

```
$ php phpmd.phar /path/to/code/ xml codesize  --reportfile '/path/to/results/phpmd_codesize_output.xml'
PHP Fatal error:  Uncaught PharException: phar "/path/to/phpqatools/phpmd.phar" SHA512 signature could not be verified: broken signature in /path/to/phpqatools/phpmd.phar:8
Stack trace:
#0 /path/to/phpqatools/phpmd.phar(8): Phar::mapPhar('phpmd.phar')
#1 {main}
  thrown in /path/to/phpqatools/phpmd.phar on line 8
```

**Comment by ravage84** [comment] 2016-06-27 11:42
Duplicate of #332

**Closed by ravage84** 2016-06-27 11:42 UTC
Labels: Bug
