### ISSUE TITLE
Using Symmetric array destructuring throws errors in phpmd

### ISSUE THREAD

**Issue by chadidi** [phpmd/phpmd#728] opened 2020-01-25 15:18 UTC
- PHPMD version: 2.7
- PHP Version: 7.3
- Installation type: composer
- Operating System / Distribution & Version: (ubuntu server) on mac os machine

I get: `Avoid using undefined variables such as '$latitude' which will lead to PHP notices.`

### Expected Behavior
no such error.

### Steps To Reproduce:
```
[$latitude, $longitude] = ['35.567211', '-5.371620'];
# then try to use them!

**Comment by kylekatarnls** [comment] 2020-01-25 15:38
Thanks. I close as this is a duplicate of #725

**Closed** 2020-01-25 15:39 UTC

**Comment by kylekatarnls** [comment] 2020-05-21 19:48
This should be fixed with #770 and you can yet test it requiring `"phpmd/phpmd": "dev-master"`
