### ISSUE TITLE
Unexpected token when using group use declarations

### ISSUE THREAD

**Issue by radmen** [phpmd/phpmd#327] opened 2015-11-16 19:42 UTC
When group use statements are used PHPMD returns error:

```
/var/www/html/src/WebPlugin/Api/Jwt/TokenFactory.php    -   Unexpected token: {, line: 5, col: 18, file: /var/www/html/src/WebPlugin/Api/Jwt/TokenFactory.php
```

Example code:

``` php
<?php

namespace WebPlugin\Api\Jwt;

use Lcobucci\JWT\{
    Builder,
    Token,
    Parser,
    Signer\Hmac\Sha256
};
use Illuminate\Http\Request;
```

PHPMD version `2.3.2`

**Comment by ravage84** [comment] 2015-11-23 09:26
I assume the problem lies in pdepend

**Comment by JeroenDeDauw** [comment] 2016-05-29 12:18
This is a duplicate of https://github.com/phpmd/phpmd/issues/279

**Comment by ravage84** [comment] 2016-05-29 12:36
@JeroenDeDauw it's related but not a full duplicate, that's why I keep it open. Thanks for noting.

**Comment by JeroenDeDauw** [comment] 2016-05-29 13:00
Apparently I misread this issue. Indeed not a duplicate at all

**Comment by torkiljohnsen** [comment] 2016-12-20 09:56
One year later, this is still an issue in PHPMD. Are there any related pdepend issue for this?

**Comment by ravage84** [comment] 2016-12-20 10:48
@torkiljohnsen haven't found any. Pleas open one and link it with this issue. Thanks.

**Comment by torkiljohnsen** [comment] 2017-01-06 10:22
🎉  👍

**Comment by PierreLvx** [comment] 2017-01-06 10:53
Just tested here. I am afraid this is only a partial fix.

We no longer have issues with files using a single group use declaration. However, with more than one group there comes the `Unexpected token` again.

Unfortunately, I don't have the time to dig deeper right now.

**Comment by manuelpichler** [comment] 2017-01-06 11:41
@PierreLvx could you please provide example code that fails?

**Comment by PierreLvx** [comment] 2017-01-11 16:53
We narrowed it down to one package (https://github.com/stripe/stripe-php), which we use with Laravel 5.

If we do :

```php
use Stripe\{
    Stripe,
    Coupon,
    Customer,
    Subscription
};
```

The tests fail.

Actually, any of the following use statement will fail :

```php
use SomeNamespace\{
   Foo,
   Bar
};
```

However, something like this will pass :

```php
use SomeOtherNameSpace\Names\{
   Bob,
   Alice
};

**Comment by manuelpichler** [comment] 2017-01-11 17:35
@PierreLvx thx for this reproducible, I will investigate asap.

**Closed** 2017-01-16 14:45 UTC
Labels: Bug, PDepend
