### ISSUE TITLE
yield keyword

### ISSUE THREAD

**Issue by pmiroslawski** [phpmd/phpmd#438] opened 2017-02-07 10:41 UTC
I get this when I want to run a phpmd (PHPMD 2.6.0):
Unexpected token: yield from

Generators:
http://php.net/manual/pl/language.generators.syntax.php

**Comment by emirb** [comment] 2017-12-06 17:33
Addressed in https://github.com/pdepend/pdepend/pull/350

**Comment by tvbeek** [comment] 2019-09-24 15:19
@pmiroslawski did you run it with the phar file or the composer package?

**Comment by kylekatarnls** [comment] 2019-09-24 17:40
I can't reproduce either, as pdepend/pdepend#350 was merged, this was probably fixed since.

**Closed by kylekatarnls** 2019-09-24 17:40 UTC
Labels: Bug, PDepend
